config/routes.rb
Simpleman::Application.routes.draw do
  resources :manuals

  get "home/index"
root :to => "home#index"

end

app/models/manual.rb
class Manual < ActiveRecord::Base
    attr_accessible :name, :value, :brief
    validates :name, :presence => true
    validates :value, :presence => true

    define_index do
        indexes [ brief, value ], 
            :as => :bvalue
    end
#    define_index do
#        #fields
#        indexes value, :sortable => true
#        indexes brief, :sortable => true
#        #attributes
#    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  # GET /manuals
  # GET /manuals.xml
  def index
    @manuals = Manual.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @manuals }
    end
  end

  # GET /manuals/1
  # GET /manuals/1.xml
  def show
    @manual = Manual.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @manual }
    end
  end

  # GET /manuals/new
  # GET /manuals/new.xml
  def new
    @manual = Manual.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @manual }
    end
  end

  # GET /manuals/1/edit
  def edit
    @manual = Manual.find(params[:id])
  end

  # POST /manuals
  # POST /manuals.xml
  def create
    @manual = Manual.new(params[:manual])

    respond_to do |format|
      if @manual.save
        format.html { redirect_to(@manual, :notice => 'Manual was successfully created.') }
        format.xml  { render :xml => @manual, :status => :created, :location => @manual }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @manual.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /manuals/1
  # PUT /manuals/1.xml
  def update
    @manual = Manual.find(params[:id])

    respond_to do |format|
      if @manual.update_attributes(params[:manual])
        format.html { redirect_to(@manual, :notice => 'Manual was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @manual.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /manuals/1
  # DELETE /manuals/1.xml
  def destroy
    @manual = Manual.find(params[:id])
    @manual.destroy

    respond_to do |format|
      format.html { redirect_to(manuals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/views/home/index.html.erb
<div class="container">
    <div id="leftside">
        <h1>Ask me.</h1>
        <h2>I know geek stuff.</h2>
    </div>
    <div id="rightside">
        <%= form_for(@manual) do |f| %>
            <%= f.text_field :svalue %>
            <%= f.submit "Search" %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleman</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= stylesheet_link_tag 'css', :media => 'screen' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/manuals/_form.html.erb
<%= form_for(@manual) do |f| %>
  <% if @manual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manual.errors.count, "error") %> prohibited this manual from being saved:</h2>

      <ul>
      <% @manual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_area :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manuals/edit.html.erb
<h1>Editing manual</h1>

<%= render 'form' %>

<%= link_to 'Show', @manual %> |
<%= link_to 'Back', manuals_path %>

app/views/manuals/index.html.erb
<h1>Listing manuals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @manuals.each do |manual| %>
  <tr>
    <td><%= manual.name %></td>
    <td><%= manual.value %></td>
    <td><%= link_to 'Show', manual %></td>
    <td><%= link_to 'Edit', edit_manual_path(manual) %></td>
    <td><%= link_to 'Destroy', manual, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Manual', new_manual_path %>

app/views/manuals/new.html.erb
<h1>New manual</h1>

<%= render 'form' %>

<%= link_to 'Back', manuals_path %>

app/views/manuals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @manual.name %>
</p>

<p>
  <b>Value:</b>
  <%= @manual.value %>
</p>


<%= link_to 'Edit', edit_manual_path(@manual) %> |
<%= link_to 'Back', manuals_path %>